
package com.coll.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AllServicePortType", targetNamespace = "http://webservice.coll.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AllServicePortType {


    /**
     * 
     * @param context
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getDivideWord")
    @WebResult(targetNamespace = "http://webservice.coll.com")
    @RequestWrapper(localName = "getDivideWord", targetNamespace = "http://webservice.coll.com", className = "com.coll.webservice.GetDivideWord")
    @ResponseWrapper(localName = "getDivideWordResponse", targetNamespace = "http://webservice.coll.com", className = "com.coll.webservice.GetDivideWordResponse")
    public String getDivideWord(
        @WebParam(name = "context", targetNamespace = "http://webservice.coll.com")
        String context);

    /**
     * 
     * @param context
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getArrayDivideWords")
    @WebResult(targetNamespace = "http://webservice.coll.com")
    @RequestWrapper(localName = "getArrayDivideWords", targetNamespace = "http://webservice.coll.com", className = "com.coll.webservice.GetArrayDivideWords")
    @ResponseWrapper(localName = "getArrayDivideWordsResponse", targetNamespace = "http://webservice.coll.com", className = "com.coll.webservice.GetArrayDivideWordsResponse")
    public String getArrayDivideWords(
        @WebParam(name = "context", targetNamespace = "http://webservice.coll.com")
        List<String> context);

    /**
     * 
     * @param href
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getHtmlMeta")
    @WebResult(targetNamespace = "http://webservice.coll.com")
    @RequestWrapper(localName = "getHtmlMeta", targetNamespace = "http://webservice.coll.com", className = "com.coll.webservice.GetHtmlMeta")
    @ResponseWrapper(localName = "getHtmlMetaResponse", targetNamespace = "http://webservice.coll.com", className = "com.coll.webservice.GetHtmlMetaResponse")
    public String getHtmlMeta(
        @WebParam(name = "href", targetNamespace = "http://webservice.coll.com")
        String href);

    /**
     * 
     * @param imgAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getBase64")
    @WebResult(targetNamespace = "http://webservice.coll.com")
    @RequestWrapper(localName = "getBase64", targetNamespace = "http://webservice.coll.com", className = "com.coll.webservice.GetBase64")
    @ResponseWrapper(localName = "getBase64Response", targetNamespace = "http://webservice.coll.com", className = "com.coll.webservice.GetBase64Response")
    public String getBase64(
        @WebParam(name = "imgAddress", targetNamespace = "http://webservice.coll.com")
        String imgAddress);

}
