
package com.coll.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AllService", targetNamespace = "http://webservice.coll.com", wsdlLocation = "http://localhost:8080/CollWebService/services/AllService?wsdl")
public class AllService
    extends Service
{

    private final static URL ALLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALLSERVICE_EXCEPTION;
    private final static QName ALLSERVICE_QNAME = new QName("http://webservice.coll.com", "AllService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CollWebService/services/AllService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALLSERVICE_WSDL_LOCATION = url;
        ALLSERVICE_EXCEPTION = e;
    }

    public AllService() {
        super(__getWsdlLocation(), ALLSERVICE_QNAME);
    }

    public AllService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALLSERVICE_QNAME, features);
    }

    public AllService(URL wsdlLocation) {
        super(wsdlLocation, ALLSERVICE_QNAME);
    }

    public AllService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALLSERVICE_QNAME, features);
    }

    public AllService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AllService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AllServicePortType
     */
    @WebEndpoint(name = "AllServiceHttpSoap11Endpoint")
    public AllServicePortType getAllServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://webservice.coll.com", "AllServiceHttpSoap11Endpoint"), AllServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AllServicePortType
     */
    @WebEndpoint(name = "AllServiceHttpSoap11Endpoint")
    public AllServicePortType getAllServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.coll.com", "AllServiceHttpSoap11Endpoint"), AllServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALLSERVICE_EXCEPTION!= null) {
            throw ALLSERVICE_EXCEPTION;
        }
        return ALLSERVICE_WSDL_LOCATION;
    }

}
